trigger: none

variables:
  - group: hcs-credentials

stages:
  - stage: Bootstrap
    jobs:
      - template: ../templates/stage-validate.yml
  - stage: PlanAll
    dependsOn: Bootstrap
    jobs:
      - template: ../templates/stage-plan.yml
  - stage: ApplyAll
    dependsOn: PlanAll
    jobs:
      - template: ../templates/stage-apply.yml
